site_name: PROVESID Documentation
site_description: A Python package for chemical identifier resolution and experimental property extraction
site_author: PROVESID Team
site_url: https://usetox.github.io/PROVESID/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - Tutorials:
    - PubChem Tutorial: examples/pubchem/pubchem_tutorial.ipynb
    - CAS Common Chemistry: examples/CCC/CAS_Common_Chemistry_tutorial.ipynb
    - ChEBI Tutorial: examples/ChEBI/ChEBI_tutorial.ipynb
    - ClassyFire Tutorial: examples/ClassyFire/classyfire_tutorial.ipynb
    - OPSIN Tutorial: examples/OPSIN/opsin_tutorial.ipynb
    - Chemical ID Resolver: examples/resolver/chem_id_resolver_tutorial.ipynb
  - API Reference:
    - Overview: api/index.md
    - PubChem API: api/pubchem.md
    - PubChem View: api/pubchemview.md
    - NCI Resolver: api/nci_resolver.md
    - Common Chemistry: api/cascommonchem.md
    - ClassyFire: api/classyfire.md
    - OPSIN: api/opsin.md
    - ChEBI: api/chebi.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      allow_errors: false
      include_source: true
      ignore_h1_titles: true
      remove_tag_config:
        remove_input_tags:
          - hide_code
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: true
            members_order: source

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/provesid/provesid
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css
